version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: aari-web-api-postgres
    environment:
      POSTGRES_DB: aari-web-api-development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
